
ribbon.eureka.enabled: true 

server:
    port: 83

endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        sensitive: false
 
eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
    client:
      healthcheck:
        enabled: true
      registryFetchIntervalSeconds: 5
      serviceUrl:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
        

